### PR TITLE
Add Float and Int formatters

### PR DESCRIPTION
**Pull request by 514sid**
This PR adds Float and Int formatters based on my Num package, which support functionality for automatically detecting decimal separators in strings.

You can check the test file to see how it converts values based on the provided decimal separator:
https://github.com/514sid/num/blob/v1.x/tests/NumTest.php

### CODE REVIEW

**Comment by michael-rubel** [comment]
Hello @514sid! 👋

It feels that formatters are intended more for higher-level formatting than primitive operations like type conversion. Also, it seems I have similar functionality in [this package](https://github.com/michael-rubel/laravel-value-objects/blob/main/tests/Unit/Primitive/NumberTest.php#L67). It automatically converts any convention you might pass to decimal.

Still, if you want to include this particular implementation in your project, you can register these by placing them in the `Formatters` folder.

Thank you for your pull request! ❤

**Comment by 514sid** [comment]
Hi @michael-rubel,

The Num helper works a bit differently. It is more useful when you need to convert strings to integers or floats. It functions more as the opposite version of LocaleNumberFormatter.

However, thank you for your response, and feel free to merge it if you change your mind in the future.

**Comment by michael-rubel** [comment]
@514sid you can use `asFloat()` or `asInteger()` methods on the `Number` object though. If I need precision I'd anyway use string decimal. If precision is not a concern, it's better to keep it simple and just use a native PHP cast (float).

**Comment by michael-rubel** [comment]
@514sid you can use asFloat() or asInteger() methods on the Number object though.

**Comment by michael-rubel** [comment]
@514sid you can use `asFloat()` or `asInteger()` methods on the Number object though.

**Comment by michael-rubel** [comment]
@514sid you can use `asFloat()` or `asInteger()` methods on the `Number` object though.

**Pull request closed without merging**
