### PR TITLE
Add French number tests

### LINKED ISSUE #3: Add French number tests

### PR DESCRIPTION
**Pull request by khalyomede**
This PR adds french number tests.

## Added

- French number tests

## Fixed

N/A

## Breaking

N/A

### CODE REVIEW

**Comment by khalyomede** [comment]
When I run the tests, two strings look like equal, but when I serialize there is some weird invisible characters that seems to be included in the output of the NumberFormatter. 

Can you please tell me if you have the same errors @michael-rubel ?

```bash
   FAIL  MichaelRubel\Formatters\Tests\LocaleNumberFormatterTest
  ✓ can format number based on pl locale
  ✓ can format number based on en locale
  ⨯ can format number based on fr locale

  ---

  • MichaelRubel\Formatters\Tests\LocaleNumberFormatterTest > can format number based on fr locale
  Failed asserting that two strings are equal.

  at tests/LocaleNumberFormatterTest.php:97
     93▕             'number' => 10000,
     94▕             'locale' => 'fr',
     95▕         ]);
     96▕ 
  ➜  97▕         $this->assertEquals('10 000,00', $result);      
     98▕ 
     99▕         $result = format(LocaleNumberFormatter::class, [
    100▕             'number' => 10000.00,
    101▕             'locale' => 'fr',
  --- Expected
  +++ Actual
  @@ @@
  -'10 000,00'
  +'10 000,00'

  Tests:  1 failed, 15 passed
  Time:   6.53s
```

When I serialize both values, here is what I get (first is my string, second is the NumberFormatter output):

```bash
  --- Expected
  +++ Actual
  @@ @@
  -'s:9:"10 000,00";'
  +'s:11:"10 000,00";'
```

**Comment by michael-rubel** [comment]
Hello @khalyomede

It adds locale-based special characters to the output.
You could see it if you use PHPStorm:

nbsp

**Comment by michael-rubel** [comment]
I've added French characters to the tests.
Thanks for your contribution @khalyomede! 🎉 

One thing... 🤔 

Scrutinizer stands "You shall not pass" on this test despite it works on GitHub workflow and locally.
https://scrutinizer-ci.com/g/michael-rubel/laravel-formatters/inspections/05cc0709-9bf4-48f2-a283-ae32dd0acef2

I tried to clear the cache but got no luck. I've reported this issue to Scrutinizer (it's probably encoding-related from their side) so we'll wait for their response first before merging this.

**Comment by michael-rubel** [comment]
Scrutinizer has solid trouble with narrow break space.
I had to trim all special characters for this particular test.

**Pull request merged**
